-- Development seed data for the first DMK character-tracking vertical slice.
-- This migration is temporary development data.
-- Production game data will eventually be generated by the DMK Data Builder.

INSERT INTO collections (
    id,
    display_name,
    sort_order,
    is_limited_time,
    is_active,
    notes
)
VALUES (
    'collection_mickey_friends',
    'Mickey and Friends',
    1,
    0,
    1,
    NULL
);


INSERT INTO characters (
    id,
    collection_id,
    display_name,
    max_level,
    sort_order,
    is_premium,
    is_limited_time,
    is_active,
    notes
)
VALUES (
    'character_mickey_mouse',
    'collection_mickey_friends',
    'Mickey Mouse',
    10,
    1,
    0,
    0,
    1,
    NULL
);


INSERT INTO tokens (
    id,
    display_name,
    token_type,
    associated_character_id,
    associated_collection_id,
    sort_order,
    is_active,
    notes
)
VALUES
(
    'token_mickey_balloon',
    'Mickey Balloon',
    'common',
    NULL,
    'collection_mickey_friends',
    1,
    1,
    NULL
),
(
    'token_mickey_gloves',
    'Mickey Gloves',
    'unique',
    'character_mickey_mouse',
    'collection_mickey_friends',
    2,
    1,
    NULL
),
(
    'token_mickey_ears',
    'Mickey Ears Hat',
    'ears',
    'character_mickey_mouse',
    'collection_mickey_friends',
    3,
    1,
    NULL
);


-- target_level 1 represents Mickey's free, instant welcome.

INSERT INTO character_levels (
    character_id,
    target_level,
    magic_cost,
    level_time_seconds
)
VALUES
('character_mickey_mouse', 1, 0, 0),
('character_mickey_mouse', 2, 500, 31),
('character_mickey_mouse', 3, 750, 300),
('character_mickey_mouse', 4, 1150, 480),
('character_mickey_mouse', 5, 1500, 3600),
('character_mickey_mouse', 6, 1950, 7200),
('character_mickey_mouse', 7, 2550, 14400),
('character_mickey_mouse', 8, 3300, 28800),
('character_mickey_mouse', 9, 4300, 57600),
('character_mickey_mouse', 10, 5600, 86400);


INSERT INTO character_level_token_requirements (
    character_id,
    target_level,
    token_id,
    quantity
)
VALUES
-- Level 2
('character_mickey_mouse', 2, 'token_mickey_balloon', 5),
('character_mickey_mouse', 2, 'token_mickey_gloves', 2),
('character_mickey_mouse', 2, 'token_mickey_ears', 2),

-- Level 3
('character_mickey_mouse', 3, 'token_mickey_balloon', 10),
('character_mickey_mouse', 3, 'token_mickey_gloves', 3),
('character_mickey_mouse', 3, 'token_mickey_ears', 3),

-- Level 4
('character_mickey_mouse', 4, 'token_mickey_balloon', 15),
('character_mickey_mouse', 4, 'token_mickey_gloves', 5),
('character_mickey_mouse', 4, 'token_mickey_ears', 5),

-- Level 5
('character_mickey_mouse', 5, 'token_mickey_balloon', 20),
('character_mickey_mouse', 5, 'token_mickey_gloves', 10),
('character_mickey_mouse', 5, 'token_mickey_ears', 10),

-- Level 6
('character_mickey_mouse', 6, 'token_mickey_balloon', 25),
('character_mickey_mouse', 6, 'token_mickey_gloves', 15),
('character_mickey_mouse', 6, 'token_mickey_ears', 15),

-- Level 7
('character_mickey_mouse', 7, 'token_mickey_balloon', 30),
('character_mickey_mouse', 7, 'token_mickey_gloves', 20),
('character_mickey_mouse', 7, 'token_mickey_ears', 20),

-- Level 8
('character_mickey_mouse', 8, 'token_mickey_balloon', 35),
('character_mickey_mouse', 8, 'token_mickey_gloves', 25),
('character_mickey_mouse', 8, 'token_mickey_ears', 25),

-- Level 9
('character_mickey_mouse', 9, 'token_mickey_balloon', 40),
('character_mickey_mouse', 9, 'token_mickey_gloves', 30),
('character_mickey_mouse', 9, 'token_mickey_ears', 30),

-- Level 10
('character_mickey_mouse', 10, 'token_mickey_balloon', 50),
('character_mickey_mouse', 10, 'token_mickey_gloves', 35),
('character_mickey_mouse', 10, 'token_mickey_ears', 35);